### ISSUE TITLE
bettermap crashes

### ISSUE THREAD

**Issue by Hanuko33** [BetterMap/BetterMap#37]
this is what is on /ct console js:
org.mozilla.javascript.EcmaError: SyntaxError: Expected end of stream at char 1636 (file:/media/data/<my home dir>/.minecraft/hs/config/ChatTriggers/modules/BetterMap/Extra/Settings/SettingsManager.js#21)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4642)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4622)
	at org.mozilla.javascript.NativeJSON.parse(NativeJSON.java:130)
	at org.mozilla.javascript.NativeJSON.execIdCall(NativeJSON.java:99)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:90)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:29)
	at BetterMap_Extra_Settings_SettingsManager_js_179._c_SettingsManager_1(BetterMap/Extra/Settings/SettingsManager.js:21)
	at BetterMap_Extra_Settings_SettingsManager_js_179.call(BetterMap/Extra/Settings/SettingsManager.js)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:436)
	at BetterMap_Extra_Settings_SettingsManager_js_179.construct(BetterMap/Extra/Settings/SettingsManager.js)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2960)
	at BetterMap_index_js_144._c_script_0(BetterMap/index.js:29)
	at BetterMap_index_js_144.call(BetterMap/index.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:342)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3951)
	at BetterMap_index_js_144.call(BetterMap/index.js)
	at BetterMap_index_js_144.exec(BetterMap/index.js)
	at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:351)
	at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:302)
	at com.chattriggers.ctjs.engine.langs.js.JSLoader$CTRequire.loadCTModule(JSLoader.kt:329)

**Comment by Hanuko33** [comment]
I looked at the discord, and downloaded all assets and... That's what it shows now
Error loading module BetterMap
org.mozilla.javascript.EcmaError: SyntaxError: Expected end of stream at char 1636 (file:/media/data/hanuko33/.minecraft/hs/config/ChatTriggers/modules/BetterMap/Extra/Settings/SettingsManager.js#21)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4642)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4622)
	at org.mozilla.javascript.NativeJSON.parse(NativeJSON.java:130)
	at org.mozilla.javascript.NativeJSON.execIdCall(NativeJSON.java:99)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:90)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:29)
	at BetterMap_Extra_Settings_SettingsManager_js_1874._c_SettingsManager_1(BetterMap/Extra/Settings/SettingsManager.js:21)
	at BetterMap_Extra_Settings_SettingsManager_js_1874.call(BetterMap/Extra/Settings/SettingsManager.js)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:436)
	at BetterMap_Extra_Settings_SettingsManager_js_1874.construct(BetterMap/Extra/Settings/SettingsManager.js)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2960)
	at BetterMap_index_js_1839._c_script_0(BetterMap/index.js:29)
	at BetterMap_index_js_1839.call(BetterMap/index.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:342)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3951)
	at BetterMap_index_js_1839.call(BetterMap/index.js)
	at BetterMap_index_js_1839.exec(BetterMap/index.js)
	at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:351)
	at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:302)
	at com.chattriggers.ctjs.engine.langs.js.JSLoader$CTRequire.loadCTModule(JSLoader.kt:329)

Command with name bcore already exists! This will not override the other command with the same name. To override conflicting commands, set the 2nd argument in setName() to true.
Command with name copykey already exists! This will not override the other command with the same name. To override conflicting commands, set the 2nd argument in setName() to true.
Command with name showarea already exists! This will not override the other command with the same name. To override conflicting commands, set the 2nd argument in setName() to true.
Command with name cw already exists! This will not override the other command with the same name. To override conflicting commands, set the 2nd argument in setName() to true.
Command with name fetchdiscord already exists! This will not override the other command with the same name. To override conflicting commands, set the 2nd argument in setName() to true.
connecting to soopy socket
java.lang.IllegalStateException
	at org.mozilla.javascript.ScriptRuntime.storeScriptable(ScriptRuntime.java:4798)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2870)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:90)
	at Coleweight_render_BaseGui_js_1774._c_anonymous_4(Coleweight/render/BaseGui.js:32)
	at Coleweight_render_BaseGui_js_1774.call(Coleweight/render/BaseGui.js)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:40)
	at com.chattriggers.ctjs.engine.langs.js.JSLoader.trigger(JSLoader.kt:298)

java.lang.IllegalStateException
	at org.mozilla.javascript.ScriptRuntime.storeScriptable(ScriptRuntime.java:4798)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2870)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2875)
	at soopyApis_index_js_2002._c_SoopyAPI_renderOverlay_2(soopyApis/index.js:28)
	at soopyApis_index_js_2002.call(soopyApis/index.js)
	at com.chattriggers.ctjs.engine.langs.js.JSLoader.trigger(JSLoader.kt:298)

java.lang.IllegalStateException
	at org.mozilla.javascript.ScriptRuntime.storeScriptable(ScriptRuntime.java:4798)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2870)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:90)
	at SoopyV2_featureClass_featureManager_js_1894._c_triggerEvent_56(SoopyV2/featureClass/featureManager.js:450)
	at SoopyV2_featureClass_featureManager_js_1894.call(SoopyV2/featureClass/featureManager.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:38)
	at SoopyV2_featureClass_featureManager_js_1894._c_anonymous_55(SoopyV2/featureClass/featureManager.js:434)
	at SoopyV2_featureClass_featureManager_js_1894.call(SoopyV2/featureClass/featureManager.js)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:40)
	at com.chattriggers.ctjs.engine.langs.js.JSLoader.trigger(JSLoader.kt:298)

Error loading module BetterMap
java.lang.IllegalStateException
	at org.mozilla.javascript.ScriptRuntime.getTopCallScope(ScriptRuntime.java:3926)
	at org.mozilla.javascript.InterfaceAdapter.create(InterfaceAdapter.java:30)
	at org.mozilla.javascript.NativeJavaObject.createInterfaceAdapter(NativeJavaObject.java:680)
	at org.mozilla.javascript.NativeJavaObject.coerceTypeImpl(NativeJavaObject.java:656)
	at org.mozilla.javascript.Context.jsToJava(Context.java:1844)
	at org.mozilla.javascript.NativeJavaClass.constructInternal(NativeJavaClass.java:239)
	at org.mozilla.javascript.NativeJavaClass.constructSpecific(NativeJavaClass.java:190)
	at org.mozilla.javascript.NativeJavaClass.construct(NativeJavaClass.java:153)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2960)
	at BetterMap_Render_BossMapRendering_BossMapRenderer_js_2129._c_BossMapRenderer_1(BetterMap/Render/BossMapRendering/BossMapRenderer.js:13)
	at BetterMap_Render_BossMapRendering_BossMapRenderer_js_2129.call(BetterMap/Render/BossMapRendering/BossMapRenderer.js)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:436)
	at BetterMap_Render_BossMapRendering_BossMapRenderer_js_2129.construct(BetterMap/Render/BossMapRendering/BossMapRenderer.js)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2960)
	at BetterMap_Render_MapRenderer_js_2126._c_MapRenderer_1(BetterMap/Render/MapRenderer.js:13)
	at BetterMap_Render_MapRenderer_js_2126.call(BetterMap/Render/MapRenderer.js)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:436)
	at BetterMap_Render_MapRenderer_js_2126.construct(BetterMap/Render/MapRenderer.js)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2960)
	at BetterMap_index_js_2094._c_script_0(BetterMap/index.js:26)
	at BetterMap_index_js_2094.call(BetterMap/index.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:342)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3951)
	at BetterMap_index_js_2094.call(BetterMap/index.js)
	at BetterMap_index_js_2094.exec(BetterMap/index.js)
	at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:351)
	at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:302)
	at com.chattriggers.ctjs.engine.langs.js.JSLoader$CTRequire.loadCTModule(JSLoader.kt:329)

**Comment by Hanuko33** [comment]
Okay, I talked about this in the ticket. To fix this, remove your (minecraft location where you run bettermap)/config/ChatTriggers/modules/soopyAddonsData/bettermapsettings.json

ONLY THIS FILE, NOTHING ELSE
